pactbroker:
  host: "localhost"
  port: "8115"
server:
  port: 8111
eventhub:
  namespace: "bus-application"
  name: "bus"
  sasKeyName: "bsProvider"
  sasKey: "Endpoint=sb://bus-application.servicebus.windows.net/;SharedAccessKeyName=bsProvider;SharedAccessKey=mgy1S+Fsu20DhimBaVOM68Sri9ELSjX4kj0gcTGTWS0="
